## Random Numbers

This module implements pseudo-random number generators for various distributions. It uses the Mersenne Twister algorithm (https://en.wikipedia.org/wiki/Mersenne_Twister) as its core generator. It is called pseudo-random, because the numbers seem random, but are reproducabl

In [5]:
import random

## Random float number in [0,1)
a = random.random()
print(a)

## Random float number in range [a,b]
a = random.uniform(1,10)
print(a)

## Random integer in [a,b]
a = random.randint(0,10)
print(a)

## Random integer in [a,b)
a = random.randrange(0,10)
print(a)

## random float number normal distribution with mu as 0 and sigma as 1
a = random.normalvariate(0,1)
print(a)

## Random element from sequence
string1 = list('qwertyuiop')
a = random.choice(string1)
print(a)

## Choose k random elements from sequence : 
a = random.sample(string1,3)
print(a)

## choose k elemets with replacement that is elements can come twice
a = random.choices(string1,k=3)
print(a)


## shuffling the list
a = list('abcdefghi')
random.shuffle(a)
print(a)

0.33886196124074286
3.271830497307937
6
2
-0.4832947281013419
i
['q', 't', 'i']
['e', 'r', 'p']
['g', 'd', 'b', 'i', 'e', 'f', 'h', 'c', 'a']


In [7]:
## Error Raises
## Choose k unique random elements from sequence
string1 =[1,2,3,4,5,6,7]
a = random.sample(string1,8)  ## 8 larger than the list size
print(a)

ValueError: Sample larger than population or is negative

## The Seed Generator
if you use random.seed(), the randomness in the output completely gets demolished. Every time you will get the same output.

In [31]:
print('Seeding with 1...\n')

random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

## re running the above code with the same random.seed()
print('\nRe-seeding with 1...\n')
random.seed(1)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

Seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E

Re-seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E


## The SECRET Module
The secrets module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
In particularly, secrets should be used in preference to the default pseudo-random number generator in the random module, which is designed for modelling and simulation, not security or cryptography.

In [54]:
import secrets

## Random integer in [0,n)
a = secrets.randbelow(10)
print(a)

## returns an integer with k random bits
a = secrets.randbits(3)  ## randomly assigning 0 or 1 in 3 bits and then its value in decimal form
print(a)

## random elements from sequence
a = secrets.choice(list('ABCDEF'))
print(a)


8
6
D


## Random Numbers with NumPy

In [12]:
import numpy as np

## numpy array with random floats with size k
np.random.seed(1)
print(np.random.rand(3))


## seeing the seeding method
np.random.seed(42)
print(np.random.rand(3))

np.random.seed(1)
print(np.random.rand(3))

## array with random integers with size n in range of [a,b)
a = np.random.randint(0,10,(5,3))
print(a)


# generate nd array with Gaussian values, array has size n
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
a = np.random.randn(5)
print(a)

## shuffling the array 
## just shuffles the row sequence
## row 1 to row 3 and so on.........
a = np.array([[1,2,3],[4,5,6],[7,8,9],[9,10,11]])
print(a)
np.random.shuffle(a)
print("Shuffled array")
print(a)


[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[0.37454012 0.95071431 0.73199394]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]
[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]
Shuffled array
[[ 7  8  9]
 [ 4  5  6]
 [ 9 10 11]
 [ 1  2  3]]


In [16]:
a = 256
b = 256
a is b

True

In [17]:
sorted([1,2,5,9,0])

[0, 1, 2, 5, 9]